// source: vosk_stt.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.vosk.stt.v1.RecognitionConfig', null, global);
goog.exportSymbol('proto.vosk.stt.v1.RecognitionSpec', null, global);
goog.exportSymbol('proto.vosk.stt.v1.RecognitionSpec.AudioEncoding', null, global);
goog.exportSymbol('proto.vosk.stt.v1.SpeechRecognitionAlternative', null, global);
goog.exportSymbol('proto.vosk.stt.v1.SpeechRecognitionChunk', null, global);
goog.exportSymbol('proto.vosk.stt.v1.StatsResponse', null, global);
goog.exportSymbol('proto.vosk.stt.v1.StreamingRecognitionRequest', null, global);
goog.exportSymbol('proto.vosk.stt.v1.StreamingRecognitionRequest.StreamingRequestCase', null, global);
goog.exportSymbol('proto.vosk.stt.v1.StreamingRecognitionResponse', null, global);
goog.exportSymbol('proto.vosk.stt.v1.WordInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.StreamingRecognitionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.vosk.stt.v1.StreamingRecognitionRequest.oneofGroups_);
};
goog.inherits(proto.vosk.stt.v1.StreamingRecognitionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.StreamingRecognitionRequest.displayName = 'proto.vosk.stt.v1.StreamingRecognitionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.StreamingRecognitionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vosk.stt.v1.StreamingRecognitionResponse.repeatedFields_, null);
};
goog.inherits(proto.vosk.stt.v1.StreamingRecognitionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.StreamingRecognitionResponse.displayName = 'proto.vosk.stt.v1.StreamingRecognitionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.RecognitionConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vosk.stt.v1.RecognitionConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.RecognitionConfig.displayName = 'proto.vosk.stt.v1.RecognitionConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.RecognitionSpec = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vosk.stt.v1.RecognitionSpec, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.RecognitionSpec.displayName = 'proto.vosk.stt.v1.RecognitionSpec';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.SpeechRecognitionChunk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vosk.stt.v1.SpeechRecognitionChunk.repeatedFields_, null);
};
goog.inherits(proto.vosk.stt.v1.SpeechRecognitionChunk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.SpeechRecognitionChunk.displayName = 'proto.vosk.stt.v1.SpeechRecognitionChunk';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vosk.stt.v1.SpeechRecognitionAlternative.repeatedFields_, null);
};
goog.inherits(proto.vosk.stt.v1.SpeechRecognitionAlternative, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.SpeechRecognitionAlternative.displayName = 'proto.vosk.stt.v1.SpeechRecognitionAlternative';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.WordInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vosk.stt.v1.WordInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.WordInfo.displayName = 'proto.vosk.stt.v1.WordInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vosk.stt.v1.StatsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vosk.stt.v1.StatsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vosk.stt.v1.StatsResponse.displayName = 'proto.vosk.stt.v1.StatsResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.StreamingRequestCase = {
  STREAMING_REQUEST_NOT_SET: 0,
  CONFIG: 1,
  AUDIO_CONTENT: 2
};

/**
 * @return {proto.vosk.stt.v1.StreamingRecognitionRequest.StreamingRequestCase}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.getStreamingRequestCase = function() {
  return /** @type {proto.vosk.stt.v1.StreamingRecognitionRequest.StreamingRequestCase} */(jspb.Message.computeOneofCase(this, proto.vosk.stt.v1.StreamingRecognitionRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.StreamingRecognitionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.StreamingRecognitionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    config: (f = msg.getConfig()) && proto.vosk.stt.v1.RecognitionConfig.toObject(includeInstance, f),
    audioContent: msg.getAudioContent_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.StreamingRecognitionRequest}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.StreamingRecognitionRequest;
  return proto.vosk.stt.v1.StreamingRecognitionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.StreamingRecognitionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.StreamingRecognitionRequest}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.vosk.stt.v1.RecognitionConfig;
      reader.readMessage(value,proto.vosk.stt.v1.RecognitionConfig.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAudioContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.StreamingRecognitionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.StreamingRecognitionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.vosk.stt.v1.RecognitionConfig.serializeBinaryToWriter
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional RecognitionConfig config = 1;
 * @return {?proto.vosk.stt.v1.RecognitionConfig}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.getConfig = function() {
  return /** @type{?proto.vosk.stt.v1.RecognitionConfig} */ (
    jspb.Message.getWrapperField(this, proto.vosk.stt.v1.RecognitionConfig, 1));
};


/**
 * @param {?proto.vosk.stt.v1.RecognitionConfig|undefined} value
 * @return {!proto.vosk.stt.v1.StreamingRecognitionRequest} returns this
*/
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.setConfig = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.vosk.stt.v1.StreamingRecognitionRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vosk.stt.v1.StreamingRecognitionRequest} returns this
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.clearConfig = function() {
  return this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes audio_content = 2;
 * @return {!(string|Uint8Array)}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.getAudioContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes audio_content = 2;
 * This is a type-conversion wrapper around `getAudioContent()`
 * @return {string}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.getAudioContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAudioContent()));
};


/**
 * optional bytes audio_content = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAudioContent()`
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.getAudioContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAudioContent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.vosk.stt.v1.StreamingRecognitionRequest} returns this
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.setAudioContent = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.vosk.stt.v1.StreamingRecognitionRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vosk.stt.v1.StreamingRecognitionRequest} returns this
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.clearAudioContent = function() {
  return jspb.Message.setOneofField(this, 2, proto.vosk.stt.v1.StreamingRecognitionRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vosk.stt.v1.StreamingRecognitionRequest.prototype.hasAudioContent = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.StreamingRecognitionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.StreamingRecognitionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    chunksList: jspb.Message.toObjectList(msg.getChunksList(),
    proto.vosk.stt.v1.SpeechRecognitionChunk.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.StreamingRecognitionResponse}
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.StreamingRecognitionResponse;
  return proto.vosk.stt.v1.StreamingRecognitionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.StreamingRecognitionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.StreamingRecognitionResponse}
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.vosk.stt.v1.SpeechRecognitionChunk;
      reader.readMessage(value,proto.vosk.stt.v1.SpeechRecognitionChunk.deserializeBinaryFromReader);
      msg.addChunks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.StreamingRecognitionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.StreamingRecognitionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChunksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.vosk.stt.v1.SpeechRecognitionChunk.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SpeechRecognitionChunk chunks = 1;
 * @return {!Array<!proto.vosk.stt.v1.SpeechRecognitionChunk>}
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.prototype.getChunksList = function() {
  return /** @type{!Array<!proto.vosk.stt.v1.SpeechRecognitionChunk>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vosk.stt.v1.SpeechRecognitionChunk, 1));
};


/**
 * @param {!Array<!proto.vosk.stt.v1.SpeechRecognitionChunk>} value
 * @return {!proto.vosk.stt.v1.StreamingRecognitionResponse} returns this
*/
proto.vosk.stt.v1.StreamingRecognitionResponse.prototype.setChunksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.vosk.stt.v1.SpeechRecognitionChunk=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vosk.stt.v1.SpeechRecognitionChunk}
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.prototype.addChunks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.vosk.stt.v1.SpeechRecognitionChunk, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vosk.stt.v1.StreamingRecognitionResponse} returns this
 */
proto.vosk.stt.v1.StreamingRecognitionResponse.prototype.clearChunksList = function() {
  return this.setChunksList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.RecognitionConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.RecognitionConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.RecognitionConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.RecognitionConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    specification: (f = msg.getSpecification()) && proto.vosk.stt.v1.RecognitionSpec.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.RecognitionConfig}
 */
proto.vosk.stt.v1.RecognitionConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.RecognitionConfig;
  return proto.vosk.stt.v1.RecognitionConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.RecognitionConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.RecognitionConfig}
 */
proto.vosk.stt.v1.RecognitionConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.vosk.stt.v1.RecognitionSpec;
      reader.readMessage(value,proto.vosk.stt.v1.RecognitionSpec.deserializeBinaryFromReader);
      msg.setSpecification(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.RecognitionConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.RecognitionConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.RecognitionConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.RecognitionConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpecification();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.vosk.stt.v1.RecognitionSpec.serializeBinaryToWriter
    );
  }
};


/**
 * optional RecognitionSpec specification = 1;
 * @return {?proto.vosk.stt.v1.RecognitionSpec}
 */
proto.vosk.stt.v1.RecognitionConfig.prototype.getSpecification = function() {
  return /** @type{?proto.vosk.stt.v1.RecognitionSpec} */ (
    jspb.Message.getWrapperField(this, proto.vosk.stt.v1.RecognitionSpec, 1));
};


/**
 * @param {?proto.vosk.stt.v1.RecognitionSpec|undefined} value
 * @return {!proto.vosk.stt.v1.RecognitionConfig} returns this
*/
proto.vosk.stt.v1.RecognitionConfig.prototype.setSpecification = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vosk.stt.v1.RecognitionConfig} returns this
 */
proto.vosk.stt.v1.RecognitionConfig.prototype.clearSpecification = function() {
  return this.setSpecification(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vosk.stt.v1.RecognitionConfig.prototype.hasSpecification = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.RecognitionSpec.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.RecognitionSpec} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.RecognitionSpec.toObject = function(includeInstance, msg) {
  var f, obj = {
    audioEncoding: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sampleRateHertz: jspb.Message.getFieldWithDefault(msg, 2, 0),
    languageCode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    profanityFilter: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    model: jspb.Message.getFieldWithDefault(msg, 5, ""),
    partialResults: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    singleUtterance: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    rawResults: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    maxAlternatives: jspb.Message.getFieldWithDefault(msg, 11, 0),
    enableWordTimeOffsets: jspb.Message.getBooleanFieldWithDefault(msg, 12, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.RecognitionSpec}
 */
proto.vosk.stt.v1.RecognitionSpec.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.RecognitionSpec;
  return proto.vosk.stt.v1.RecognitionSpec.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.RecognitionSpec} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.RecognitionSpec}
 */
proto.vosk.stt.v1.RecognitionSpec.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.vosk.stt.v1.RecognitionSpec.AudioEncoding} */ (reader.readEnum());
      msg.setAudioEncoding(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSampleRateHertz(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProfanityFilter(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setModel(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPartialResults(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSingleUtterance(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRawResults(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxAlternatives(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableWordTimeOffsets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.RecognitionSpec.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.RecognitionSpec} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.RecognitionSpec.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAudioEncoding();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getSampleRateHertz();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getProfanityFilter();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getModel();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPartialResults();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getSingleUtterance();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getRawResults();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getMaxAlternatives();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getEnableWordTimeOffsets();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.vosk.stt.v1.RecognitionSpec.AudioEncoding = {
  AUDIO_ENCODING_UNSPECIFIED: 0,
  LINEAR16_PCM: 1
};

/**
 * optional AudioEncoding audio_encoding = 1;
 * @return {!proto.vosk.stt.v1.RecognitionSpec.AudioEncoding}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getAudioEncoding = function() {
  return /** @type {!proto.vosk.stt.v1.RecognitionSpec.AudioEncoding} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.vosk.stt.v1.RecognitionSpec.AudioEncoding} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setAudioEncoding = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int64 sample_rate_hertz = 2;
 * @return {number}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getSampleRateHertz = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setSampleRateHertz = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string language_code = 3;
 * @return {string}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setLanguageCode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool profanity_filter = 4;
 * @return {boolean}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getProfanityFilter = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setProfanityFilter = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string model = 5;
 * @return {string}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setModel = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool partial_results = 7;
 * @return {boolean}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getPartialResults = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setPartialResults = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool single_utterance = 8;
 * @return {boolean}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getSingleUtterance = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setSingleUtterance = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool raw_results = 10;
 * @return {boolean}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getRawResults = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setRawResults = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional int32 max_alternatives = 11;
 * @return {number}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getMaxAlternatives = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setMaxAlternatives = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional bool enable_word_time_offsets = 12;
 * @return {boolean}
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.getEnableWordTimeOffsets = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vosk.stt.v1.RecognitionSpec} returns this
 */
proto.vosk.stt.v1.RecognitionSpec.prototype.setEnableWordTimeOffsets = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.SpeechRecognitionChunk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.SpeechRecognitionChunk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.toObject = function(includeInstance, msg) {
  var f, obj = {
    alternativesList: jspb.Message.toObjectList(msg.getAlternativesList(),
    proto.vosk.stt.v1.SpeechRecognitionAlternative.toObject, includeInstance),
    pb_final: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    endOfUtterance: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.SpeechRecognitionChunk}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.SpeechRecognitionChunk;
  return proto.vosk.stt.v1.SpeechRecognitionChunk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.SpeechRecognitionChunk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.SpeechRecognitionChunk}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.vosk.stt.v1.SpeechRecognitionAlternative;
      reader.readMessage(value,proto.vosk.stt.v1.SpeechRecognitionAlternative.deserializeBinaryFromReader);
      msg.addAlternatives(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFinal(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEndOfUtterance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.SpeechRecognitionChunk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.SpeechRecognitionChunk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlternativesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.vosk.stt.v1.SpeechRecognitionAlternative.serializeBinaryToWriter
    );
  }
  f = message.getFinal();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getEndOfUtterance();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * repeated SpeechRecognitionAlternative alternatives = 1;
 * @return {!Array<!proto.vosk.stt.v1.SpeechRecognitionAlternative>}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.getAlternativesList = function() {
  return /** @type{!Array<!proto.vosk.stt.v1.SpeechRecognitionAlternative>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vosk.stt.v1.SpeechRecognitionAlternative, 1));
};


/**
 * @param {!Array<!proto.vosk.stt.v1.SpeechRecognitionAlternative>} value
 * @return {!proto.vosk.stt.v1.SpeechRecognitionChunk} returns this
*/
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.setAlternativesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.vosk.stt.v1.SpeechRecognitionAlternative=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vosk.stt.v1.SpeechRecognitionAlternative}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.addAlternatives = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.vosk.stt.v1.SpeechRecognitionAlternative, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vosk.stt.v1.SpeechRecognitionChunk} returns this
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.clearAlternativesList = function() {
  return this.setAlternativesList([]);
};


/**
 * optional bool final = 2;
 * @return {boolean}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.getFinal = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vosk.stt.v1.SpeechRecognitionChunk} returns this
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.setFinal = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool end_of_utterance = 3;
 * @return {boolean}
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.getEndOfUtterance = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vosk.stt.v1.SpeechRecognitionChunk} returns this
 */
proto.vosk.stt.v1.SpeechRecognitionChunk.prototype.setEndOfUtterance = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.SpeechRecognitionAlternative.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.SpeechRecognitionAlternative} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    wordsList: jspb.Message.toObjectList(msg.getWordsList(),
    proto.vosk.stt.v1.WordInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.SpeechRecognitionAlternative}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.SpeechRecognitionAlternative;
  return proto.vosk.stt.v1.SpeechRecognitionAlternative.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.SpeechRecognitionAlternative} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.SpeechRecognitionAlternative}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    case 3:
      var value = new proto.vosk.stt.v1.WordInfo;
      reader.readMessage(value,proto.vosk.stt.v1.WordInfo.deserializeBinaryFromReader);
      msg.addWords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.SpeechRecognitionAlternative.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.SpeechRecognitionAlternative} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getWordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.vosk.stt.v1.WordInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vosk.stt.v1.SpeechRecognitionAlternative} returns this
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float confidence = 2;
 * @return {number}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.SpeechRecognitionAlternative} returns this
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * repeated WordInfo words = 3;
 * @return {!Array<!proto.vosk.stt.v1.WordInfo>}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.getWordsList = function() {
  return /** @type{!Array<!proto.vosk.stt.v1.WordInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vosk.stt.v1.WordInfo, 3));
};


/**
 * @param {!Array<!proto.vosk.stt.v1.WordInfo>} value
 * @return {!proto.vosk.stt.v1.SpeechRecognitionAlternative} returns this
*/
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.setWordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.vosk.stt.v1.WordInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vosk.stt.v1.WordInfo}
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.addWords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.vosk.stt.v1.WordInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vosk.stt.v1.SpeechRecognitionAlternative} returns this
 */
proto.vosk.stt.v1.SpeechRecognitionAlternative.prototype.clearWordsList = function() {
  return this.setWordsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.WordInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.WordInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.WordInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.WordInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    startTime: (f = msg.getStartTime()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    endTime: (f = msg.getEndTime()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    word: jspb.Message.getFieldWithDefault(msg, 3, ""),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.WordInfo}
 */
proto.vosk.stt.v1.WordInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.WordInfo;
  return proto.vosk.stt.v1.WordInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.WordInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.WordInfo}
 */
proto.vosk.stt.v1.WordInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 2:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWord(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.WordInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.WordInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.WordInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.WordInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getWord();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional google.protobuf.Duration start_time = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.vosk.stt.v1.WordInfo.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.vosk.stt.v1.WordInfo} returns this
*/
proto.vosk.stt.v1.WordInfo.prototype.setStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vosk.stt.v1.WordInfo} returns this
 */
proto.vosk.stt.v1.WordInfo.prototype.clearStartTime = function() {
  return this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vosk.stt.v1.WordInfo.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Duration end_time = 2;
 * @return {?proto.google.protobuf.Duration}
 */
proto.vosk.stt.v1.WordInfo.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 2));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.vosk.stt.v1.WordInfo} returns this
*/
proto.vosk.stt.v1.WordInfo.prototype.setEndTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vosk.stt.v1.WordInfo} returns this
 */
proto.vosk.stt.v1.WordInfo.prototype.clearEndTime = function() {
  return this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vosk.stt.v1.WordInfo.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string word = 3;
 * @return {string}
 */
proto.vosk.stt.v1.WordInfo.prototype.getWord = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vosk.stt.v1.WordInfo} returns this
 */
proto.vosk.stt.v1.WordInfo.prototype.setWord = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float confidence = 4;
 * @return {number}
 */
proto.vosk.stt.v1.WordInfo.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.WordInfo} returns this
 */
proto.vosk.stt.v1.WordInfo.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vosk.stt.v1.StatsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.vosk.stt.v1.StatsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vosk.stt.v1.StatsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.StatsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    nStreams: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nTotalStreams: jspb.Message.getFieldWithDefault(msg, 2, 0),
    maxChunkRtf: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    maxStreamRtf: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vosk.stt.v1.StatsResponse}
 */
proto.vosk.stt.v1.StatsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vosk.stt.v1.StatsResponse;
  return proto.vosk.stt.v1.StatsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vosk.stt.v1.StatsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vosk.stt.v1.StatsResponse}
 */
proto.vosk.stt.v1.StatsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNStreams(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNTotalStreams(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMaxChunkRtf(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMaxStreamRtf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vosk.stt.v1.StatsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vosk.stt.v1.StatsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vosk.stt.v1.StatsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vosk.stt.v1.StatsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNStreams();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNTotalStreams();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMaxChunkRtf();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getMaxStreamRtf();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
};


/**
 * optional int32 n_streams = 1;
 * @return {number}
 */
proto.vosk.stt.v1.StatsResponse.prototype.getNStreams = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.StatsResponse} returns this
 */
proto.vosk.stt.v1.StatsResponse.prototype.setNStreams = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 n_total_streams = 2;
 * @return {number}
 */
proto.vosk.stt.v1.StatsResponse.prototype.getNTotalStreams = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.StatsResponse} returns this
 */
proto.vosk.stt.v1.StatsResponse.prototype.setNTotalStreams = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float max_chunk_rtf = 4;
 * @return {number}
 */
proto.vosk.stt.v1.StatsResponse.prototype.getMaxChunkRtf = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.StatsResponse} returns this
 */
proto.vosk.stt.v1.StatsResponse.prototype.setMaxChunkRtf = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float max_stream_rtf = 6;
 * @return {number}
 */
proto.vosk.stt.v1.StatsResponse.prototype.getMaxStreamRtf = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.vosk.stt.v1.StatsResponse} returns this
 */
proto.vosk.stt.v1.StatsResponse.prototype.setMaxStreamRtf = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


goog.object.extend(exports, proto.vosk.stt.v1);
